//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace WorkBookObjectModelDemo1 {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(3)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Sheet3 : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnAddSheet;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnGetActiveSheet;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnGetSheetByName;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnGetSheetByIndex;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnRenameSheet;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnReOrderSheet;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnDeleteSheet;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnLoopSheets;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Sheet3(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet3", "Sheet3") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Sheet3 = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.btnAddSheet = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1DCC1A5391B8BD1467F1A3721AD6FB32234911", "1DCC1A5391B8BD1467F1A3721AD6FB32234911", this, "btnAddSheet");
            this.btnGetActiveSheet = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "2F6CBEF0A2E25D24F792AA9E2A63E514A2C4A2", "2F6CBEF0A2E25D24F792AA9E2A63E514A2C4A2", this, "btnGetActiveSheet");
            this.btnGetSheetByName = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "3D4A7B9383264934F1F3984E314B3564859C73", "3D4A7B9383264934F1F3984E314B3564859C73", this, "btnGetSheetByName");
            this.btnGetSheetByIndex = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "4AB59086144D904462D4B51545B0A5F2928E24", "4AB59086144D904462D4B51545B0A5F2928E24", this, "btnGetSheetByIndex");
            this.btnRenameSheet = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "55DBF52EB5F5195420E59C605A8C00AB157D25", "55DBF52EB5F5195420E59C605A8C00AB157D25", this, "btnRenameSheet");
            this.btnReOrderSheet = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "6EC1B11E26866B64C2A6A1A0693B2655BB1B56", "6EC1B11E26866B64C2A6A1A0693B2655BB1B56", this, "btnReOrderSheet");
            this.btnDeleteSheet = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "726181A4C7E05174B4C7979A75E1E02CE1E8F7", "726181A4C7E05174B4C7979A75E1E02CE1E8F7", this, "btnDeleteSheet");
            this.btnLoopSheets = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "8CD17A61B8D41784E508ADC3849408A1E88E78", "8CD17A61B8D41784E508ADC3849408A1E88E78", this, "btnLoopSheets");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // btnAddSheet
            // 
            this.btnAddSheet.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnAddSheet.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnAddSheet.Name = "btnAddSheet";
            this.btnAddSheet.Text = "Add New Worksheet";
            this.btnAddSheet.UseVisualStyleBackColor = false;
            // 
            // btnGetActiveSheet
            // 
            this.btnGetActiveSheet.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnGetActiveSheet.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnGetActiveSheet.Name = "btnGetActiveSheet";
            this.btnGetActiveSheet.Text = "Get Active Sheet";
            this.btnGetActiveSheet.UseVisualStyleBackColor = false;
            // 
            // btnGetSheetByName
            // 
            this.btnGetSheetByName.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnGetSheetByName.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnGetSheetByName.Name = "btnGetSheetByName";
            this.btnGetSheetByName.Text = "By Sheet Name";
            this.btnGetSheetByName.UseVisualStyleBackColor = false;
            // 
            // btnGetSheetByIndex
            // 
            this.btnGetSheetByIndex.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnGetSheetByIndex.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnGetSheetByIndex.Name = "btnGetSheetByIndex";
            this.btnGetSheetByIndex.Text = "By Sheet Index";
            this.btnGetSheetByIndex.UseVisualStyleBackColor = false;
            // 
            // btnRenameSheet
            // 
            this.btnRenameSheet.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnRenameSheet.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnRenameSheet.Name = "btnRenameSheet";
            this.btnRenameSheet.Text = "Rename Sheet";
            this.btnRenameSheet.UseVisualStyleBackColor = false;
            // 
            // btnReOrderSheet
            // 
            this.btnReOrderSheet.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnReOrderSheet.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnReOrderSheet.Name = "btnReOrderSheet";
            this.btnReOrderSheet.Text = "Re-Order Sheet";
            this.btnReOrderSheet.UseVisualStyleBackColor = false;
            // 
            // btnDeleteSheet
            // 
            this.btnDeleteSheet.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnDeleteSheet.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnDeleteSheet.Name = "btnDeleteSheet";
            this.btnDeleteSheet.Text = "Delete Sheet";
            this.btnDeleteSheet.UseVisualStyleBackColor = false;
            // 
            // btnLoopSheets
            // 
            this.btnLoopSheets.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnLoopSheets.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnLoopSheets.Name = "btnLoopSheets";
            this.btnLoopSheets.Text = "Loop Sheets";
            this.btnLoopSheets.UseVisualStyleBackColor = false;
            // 
            // Sheet3
            // 
            this.btnAddSheet.BindingContext = this.BindingContext;
            this.btnGetActiveSheet.BindingContext = this.BindingContext;
            this.btnGetSheetByName.BindingContext = this.BindingContext;
            this.btnGetSheetByIndex.BindingContext = this.BindingContext;
            this.btnRenameSheet.BindingContext = this.BindingContext;
            this.btnReOrderSheet.BindingContext = this.BindingContext;
            this.btnDeleteSheet.BindingContext = this.BindingContext;
            this.btnLoopSheets.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
    }
    
    internal sealed partial class Globals {
        
        private static Sheet3 _Sheet3;
        
        internal static Sheet3 Sheet3 {
            get {
                return _Sheet3;
            }
            set {
                if ((_Sheet3 == null)) {
                    _Sheet3 = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
