//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace WorkBookObjectModelDemo1 {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(2)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Sheet2 : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnAddWorkbook;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnGetActiveWorkbook;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnGetWorkbookName;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnGetWorkbookIndex;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnOpenWorkbook;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnSave;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnSaveAs;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnClose;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button btnLoopWorkbooks;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Sheet2(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet2", "Sheet2") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Sheet2 = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.btnAddWorkbook = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "332945732306413489F3A434344D54B6B1A7D3", "332945732306413489F3A434344D54B6B1A7D3", this, "btnAddWorkbook");
            this.btnGetActiveWorkbook = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "4DD0B34294DD5F44F6C4AAA343C42470D98974", "4DD0B34294DD5F44F6C4AAA343C42470D98974", this, "btnGetActiveWorkbook");
            this.btnGetWorkbookName = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "5E5BCCE2051C2754FCD5B9C7520D9776806E75", "5E5BCCE2051C2754FCD5B9C7520D9776806E75", this, "btnGetWorkbookName");
            this.btnGetWorkbookIndex = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "6E928E8E96F55C644DB699D2657CF8EC678406", "6E928E8E96F55C644DB699D2657CF8EC678406", this, "btnGetWorkbookIndex");
            this.btnOpenWorkbook = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "711B60E167F6707443379C557AD56C202C5997", "711B60E167F6707443379C557AD56C202C5997", this, "btnOpenWorkbook");
            this.btnSave = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "9D12842B3935FA94E97992B29780A8478736B9", "9D12842B3935FA94E97992B29780A8478736B9", this, "btnSave");
            this.btnSaveAs = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1CF543E401B200141551B9E31EFB2B4BBF5891", "1CF543E401B200141551B9E31EFB2B4BBF5891", this, "btnSaveAs");
            this.btnClose = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1644BE98014705144A41AA12134CC743322A61", "1644BE98014705144A41AA12134CC743322A61", this, "btnClose");
            this.btnLoopWorkbooks = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1626AE9DB1D96A148FA18A8C116810692056C1", "1626AE9DB1D96A148FA18A8C116810692056C1", this, "btnLoopWorkbooks");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // btnAddWorkbook
            // 
            this.btnAddWorkbook.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnAddWorkbook.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnAddWorkbook.Name = "btnAddWorkbook";
            this.btnAddWorkbook.Text = "Add Workbook";
            this.btnAddWorkbook.UseVisualStyleBackColor = false;
            // 
            // btnGetActiveWorkbook
            // 
            this.btnGetActiveWorkbook.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnGetActiveWorkbook.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnGetActiveWorkbook.Name = "btnGetActiveWorkbook";
            this.btnGetActiveWorkbook.Text = "Active Workbook";
            this.btnGetActiveWorkbook.UseVisualStyleBackColor = false;
            // 
            // btnGetWorkbookName
            // 
            this.btnGetWorkbookName.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnGetWorkbookName.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnGetWorkbookName.Name = "btnGetWorkbookName";
            this.btnGetWorkbookName.Text = "By Workbook Name";
            this.btnGetWorkbookName.UseVisualStyleBackColor = false;
            // 
            // btnGetWorkbookIndex
            // 
            this.btnGetWorkbookIndex.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnGetWorkbookIndex.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnGetWorkbookIndex.Name = "btnGetWorkbookIndex";
            this.btnGetWorkbookIndex.Text = "By Workbook Index";
            this.btnGetWorkbookIndex.UseVisualStyleBackColor = false;
            // 
            // btnOpenWorkbook
            // 
            this.btnOpenWorkbook.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnOpenWorkbook.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnOpenWorkbook.Name = "btnOpenWorkbook";
            this.btnOpenWorkbook.Text = "Open Workbook";
            this.btnOpenWorkbook.UseVisualStyleBackColor = false;
            // 
            // btnSave
            // 
            this.btnSave.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnSave.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnSave.Name = "btnSave";
            this.btnSave.Text = "Save";
            this.btnSave.UseVisualStyleBackColor = false;
            // 
            // btnSaveAs
            // 
            this.btnSaveAs.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnSaveAs.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnSaveAs.Name = "btnSaveAs";
            this.btnSaveAs.Text = "Save As";
            this.btnSaveAs.UseVisualStyleBackColor = false;
            // 
            // btnClose
            // 
            this.btnClose.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnClose.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnClose.Name = "btnClose";
            this.btnClose.Text = "Close";
            this.btnClose.UseVisualStyleBackColor = false;
            // 
            // btnLoopWorkbooks
            // 
            this.btnLoopWorkbooks.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnLoopWorkbooks.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnLoopWorkbooks.Name = "btnLoopWorkbooks";
            this.btnLoopWorkbooks.Text = "Loop Open Workbooks";
            this.btnLoopWorkbooks.UseVisualStyleBackColor = false;
            // 
            // Sheet2
            // 
            this.btnAddWorkbook.BindingContext = this.BindingContext;
            this.btnGetActiveWorkbook.BindingContext = this.BindingContext;
            this.btnGetWorkbookName.BindingContext = this.BindingContext;
            this.btnGetWorkbookIndex.BindingContext = this.BindingContext;
            this.btnOpenWorkbook.BindingContext = this.BindingContext;
            this.btnSave.BindingContext = this.BindingContext;
            this.btnSaveAs.BindingContext = this.BindingContext;
            this.btnClose.BindingContext = this.BindingContext;
            this.btnLoopWorkbooks.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
    }
    
    internal sealed partial class Globals {
        
        private static Sheet2 _Sheet2;
        
        internal static Sheet2 Sheet2 {
            get {
                return _Sheet2;
            }
            set {
                if ((_Sheet2 == null)) {
                    _Sheet2 = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
